# This is a basic workflow to help you get started with Actions

name: Non-prod Workflow

# Controls when the workflow will run
on: 
 push:
  paths:
   - 'non-prod/**'

jobs:
 
     build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CLIENT_SECRET }}

      - run: |
          az deployment group create -f ./non-prod/main.bicep -g RG001
