name: Prod Workflow

on: 
 push:
  paths:
   - 'prod/**'

jobs:
  
     build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CLIENT_SECRET }}

      - run: |
          az deployment group create -f ./prod/main.bicep -g RG001