name: Deploying Feature branch
on:
  push:
    branches:
      - 'feature01'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CLIENT_SECRET }}

     # Checkout code
    - uses: actions/checkout@v2
    - name: Azure CLI login
      uses: azure/CLI@v1
      with: 
        inlinescript: az deployment group create -f ./main.bicep -g RG001
